drop table if exists member CASCADE;
create table member
(
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

SELECT * FROM MEMBER ;
delete from member where id=2;
insert into member(name) values('spring2');